# This workflow runs after the tests to release a new version of the code

name: Release Code

on:
  workflow_run:
    workflows:
      - "Run Tests"
    branches:
      - master
      - dev
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up the Node environment
        uses: actions/setup-node@v1
        with:
          node-version: '14.17.1'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build the packages
        run: yarn build

      # We don't use the default token since it won't call the release trigger
      # It is an intentional limitation from GitHub
      # Using a custom token is a workaround
      - name: Release the code
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn release
